### ISSUE TITLE
Mutate function not working

### ISSUE THREAD

**Issue by F4Tornado** [CodingTrain/Toy-Neural-Network-JS#118]
When I call the mutate function, I get an undefined error. When I log the neural network, I get this object, stringified:

{"input_nodes":6,"hidden_nodes":16,"output_nodes":2,"weights_ih":{"rows":16,"cols":6,"data":[[-0.7588681817561556,-0.0015736164027826405,-0.7743441465419845,0.5735821968139647,0.7303167179333263,0.7536888325147988],[-0.7517714708431349,0.7002838641328841,0.5925134069842137,0.43114275027161675,0.9624881626211272,-0.09895806160282827],[-0.6589455178098218,-0.696096110441593,-0.3055149031960056,-0.024785170248342148,-0.8490996275624898,-0.5484065157264433],[-0.6310071892596323,0.26198257989207185,0.8362451249845932,0.4293335198226558,-0.7134868294454368,0.28861286889872595],[0.41637566287502237,0.17554725166346286,0.9776465636395706,-0.11094571247042762,-0.4410035141828552,0.8003457306481243],[0.0559450013271392,-0.20289033386389832,-0.9639277145577907,0.401103247877566,-0.9286951288454572,0.7427159382756345],[0.9070155968745262,-0.9364669144680655,-0.7560906229307247,0.48867174219359066,-0.42845968213807284,0.708650914339163],[0.545914487016474,-0.3452433257623624,0.617640428365037,-0.9789470504022963,-0.385002645862488,-0.1238948488074465],[-0.33333250302978534,0.8011260001261697,-0.8894792831773897,-0.304032759451089,-0.2942273171523766,-0.2575556333171858],[0.07493841291953318,-0.35217194950133957,-0.6666732072364074,0.833799198044272,0.4792160923436475,0.057940675531410246],[-0.43416678440635037,-0.11750618656444756,0.3138631606707061,0.8938704100400638,0.9597614528283631,0.6278532074456256],[-0.832164703335073,0.8992951958382109,-0.13309989725198035,0.4117830207975044,0.8118711985575024,-0.9930072620702992],[-0.36974983544839324,0.6487337398799555,-0.30299945691158037,-0.6500380850651708,-0.3129680183779202,-0.048327989224226986],[0.8070929383947547,0.4317168631718773,0.9118896155563778,-0.24689749188593524,-0.9308839764160801,-0.9198811980884236],[0.6178231884479319,-0.9647702553637196,-0.9510743115652738,0.8400054405852297,-0.5766064338654808,-0.5299711268882832],[-0.08816621615077569,-0.2902987264159558,-0.9777235663990531,-0.3317243272380863,-0.09677818226102897,0.6356317230362021]]},"weights_ho":{"rows":2,"cols":16,"data":[[0.6727526542996372,-0.641583001128716,-0.1505842332276397,0.451071824712562,0.9631220474516455,-0.20181939062522458,-0.32326463850678966,-0.44864268006435015,-0.2665950261562857,-0.7198283800126162,0.4588827650017673,0.6073685162616083,0.6187739054701211,-0.6357582982407926,0.4155009853258034,-0.2230334822016542],[-0.4245468002837849,0.49214186452740627,0.1138953958285831,-0.7946429903817247,0.3175606435671261,-0.21391910904903266,0.23745509594259806,-0.4054028550189237,-0.7598945030430335,0.3555503685605115,-0.10151091555982772,0.19047065201160684,-0.958867043242063,-0.47887629905366147,-0.9891715537045958,-0.5602175019475935]]},"bias_h":{"rows":16,"cols":1,"data":[[0.9488474625857628],[0.134590428626157],[0.7481822561245233],[-0.9782939349056812],[-0.2117200516104556],[0.33784094797994646],[0.7674850477109887],[-0.14641101265565082],[-0.7294726029199898],[-0.3105109740249459],[-0.27102778258669913],[-0.44505190484525015],[0.623598487846885],[-0.8533350107134341],[0.871087887264808],[0.12086478580130455]]},"bias_o":{"rows":2,"cols":1,"data":[[0.42492795508612424],[0.6108978126849949]]},"learning_rate":0.1,"activation_function":{}}

**Comment by F4Tornado** [comment]
I think i've figured it out

**Comment by fartass** [comment]
Is it really mutating?
Im making a copy of the bird and new bird has same weights. The copy is suppose to get mutated as well but I dont think it does.
