### ISSUE TITLE
Implementation with cpp

### ISSUE THREAD

**Issue by Mahmoud-Hashad** [CodingTrain/Toy-Neural-Network-JS#147]
Hi, I watch your playlist it is awesome.
And i made an implementation of matrix and nn classes with cpp
still working on read / write files and multi layers but every thing else works.

Here is the link to the repository [NeuralNetwork-CPP](https://github.com/Mahmoud-Hashad/NeuralNetwork-CPP)

**Comment by AWESOMENESS555** [comment]
Hey! what a coincidence. I just made my c++ version too! https://repl.it/@AWESOMENESS_555/C-Neural-Network#main.cpp
(couldn't separate the files because repl can't seem to run multiple files at once)
