### ISSUE TITLE
feedforward() function name

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Toy-Neural-Network-JS#19]
Would a better name be `guess()` or `inference()`? Or is `feedforward()` good? What is typical?

**Comment by xxMrPHDxx** [comment]
I would prefer `feedforward()` cause it define the meaning of the function

**Comment by musabkilic** [comment]
We use a function called predict() in a python package called Keras. I think predict() is a better name.

**Comment by shiffman** [comment]
@musabkilic I like `predict()`!

**Comment by musabkilic** [comment]
Cool! It seems like the best option for now. Let's see if anybody has a better idea, otherwise I will make a pull request.

**Comment by shiffman** [comment]
Let's go with `predict()`. I like the idea of aligning with the Keras API. I can of course make the change but would gladly accept a pull request @musabkilic.

**Comment by musabkilic** [comment]
Allright. I made a pull request:
 [https://github.com/CodingTrain/Toy-Neural-Network-JS/pull/23](url)

**Comment by shiffman** [comment]
Closed thanks to #23!
