### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list mnist.js line 9

### ISSUE THREAD

**Issue by rwsturm** [CodingTrain/Toy-Neural-Network-JS#93]
I found the mnist example to be broken with the following errors:

Uncaught SyntaxError: missing ) after argument list mnist.js:9
...
Uncaught ReferenceError: loadMNIST is not defined sketch.js:33

Anyone know what is going on?  I don't know enough about promises to debug.

BTW - doodle_classifier worked for me as expected

**Comment by shiffman** [comment]
Thanks for reporting! I will take a look soon if someone doesn't get to it before me!

**Comment by KeeghanM** [comment]
hey @rwsturm what are the steps to reproduce? I was interested in looking at this one but can't seem to get that error? mnist example works perfectly for me.

**Comment by rwsturm** [comment]
sup Keeghan,

Nothing out of the ordinary.  I downloaded the repository
<https://github.com/CodingTrain/Toy-Neural-Network-JS>, unzipped, and ran.
Got that error and just can't hunt it down.  I watched the live stream 4 or
5 times and played around with fixing *mnist.js* myself but alas, I could
not.  I gave up after a couple days.  Now I notice *loadBytes.js* is avail
(and working) for doodle_classifier.  Looks like that file is using a
different method and could probably be ported to replace *mnist.js*.  Was
gonna try it but if you already know the bitmapping from the raw binary
mnist data to the training and testing files...  by all means please take
the initiative.  I obviously still have a lot to learn here.

btw - I am using the 200 OK web server and a very old version of chrome.
I've tried nearly all of the p5 coding-challenges and never had a problem
before.  If you can't get the error on mnist then this could be my setup.

**Comment by rwsturm** [comment]
meant to say *loadbinary.js* not *loadBytes.js*.  loadBytes is the new function that works; loadbinary.js is the new file that contains it.

**Comment by Versatilus** [comment]
That particular file uses a feature that requires a newer version of Chrome or Firefox. Try removing `async` and `await` and see if that fixes it.

**Comment by rwsturm** [comment]
I made those changes and got a new error:

Uncaught TypeError: First argument to DataView constructor must be an
ArrayBuffer

**Comment by rwsturm** [comment]
I installed the newest version of Firefox 52.6.0 and the original mnist.js
file and example now works as expected.  I'm going to close this issue with
reason 'Promises aren't fully supported in Chrome 49'.  Thanks for your
help.

**Comment by rwsturm** [comment]
Promises aren't fully supported in Chrome 49
